### ISSUE TITLE
add info about the API key

### ISSUE THREAD

**Issue by andrewsu** [SuLab/Lit2Hybrid#12]
add an "info" icon next to the API key box with the following text:

"PubMed restricts users to three queries per second.  To increase the rate of PubMed queries, please apply for an API key by following the instructions [here](https://ncbiinsights.ncbi.nlm.nih.gov/2017/11/02/new-api-keys-for-the-e-utilities/)."

**Comment by rampeace** [comment]
![Screenshot_2020-07-11 lit2hybrid(1)](https://user-images.githubusercontent.com/15014898/87226353-c2ea0b00-c3b0-11ea-8f5d-4f8cf103c7ba.png)

![Untitled](https://user-images.githubusercontent.com/15014898/87226436-58859a80-c3b1-11ea-9691-affe742772ef.png)

Could you please help me review the screen shot. How the icon, example links and footer has turned out.

second screenshot:
A tool-tip appear on icon hover.

**Comment by andrewsu** [comment]
Those screen shots look great to me!

**Comment by rampeace** [comment]
When we are ready please give me a green light to deploy.

**Comment by andrewsu** [comment]
Yes, feel free to deploy the latest! Thanks!
