### ISSUE TITLE
log events in Google Analytics

### ISSUE THREAD

**Issue by andrewsu** [SuLab/Lit2Hybrid#15]
in closing issue #9, page loads now trigger a pageview in Google Analytics.  However, I don't believe we are tracking how many queries each user executes.  Would be good to track this using [Google Analytics Events](https://support.google.com/analytics/answer/1033068?hl=en).

**Comment by rampeace** [comment]
We are not tracking events till now. There may be few workflow where may be hook.

If the user searches for 3 terms and 2 modifiers

Option 1:  We could add 3 and 2.  Then GA log will be  Queries => Count => 5

Option 2: Log terms and modifiers separately. In this case log becomes Queries => Terms => Count 3  | Queries => Modifiers => Count 2

Option 3: Track individual clicks. The log will be like Queries => Search button click => 5 | Queries => Example links click => count => 6 | Queries => Add Terms click => 5

**Comment by andrewsu** [comment]
Hmm, good question.   I think I like option 3 where we trigger events in three scenarios -- clicking "Search", clicking an "Example query", and clicking one of the "Add Terms" links.  On a "Search" button click, can we track both the number of terms and the number of modifiers?  And you may have been suggesting this already, but on "Add Terms" can we record how many new terms were added?

**Comment by rampeace** [comment]
> can we track both the number of terms and the number of modifiers?

Yes. we will track terms and modifiers separately for every individual action. The actions are "Search", "Example query", "Add columns", "Add rows". I'm struggling to get more simple and meaningful action names. 

>  on "Add Terms" can we record how many new terms were added?

Yes. for every action, we will calculate the no. of terms and modifiers separately. Since we have same button name both for column and row, I thought action name of "Add columns" or "Add rows" might be easier . Otherwise "Add Terms", "Add Modifiers" would work. Another option might keep "Add Terms" itself for both column and row, but have "Terms" for columns and "Modifiers" for rows in event label.

The testing I'm doing now is actually piling up in the google analytics events. Based on my research, the words I'm using to test will never be able to delete from google analytics. I'm thinking we could create a separate account for testing.

**Comment by andrewsu** [comment]
All sounds great!  I think those names are fine -- agree that the columns/rows is better.  

If you can figure out a way to create a way to create a testing environment for google analytics, go for it.  If not, I don't think it's a big deal to have a few test queries intermixed with real traffic.

**Comment by rampeace** [comment]
The changes have been deployed.
